### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by huckleberrypie**

### CODE REVIEW

**Comment by bigbiff** [comment]
Hello, please sign up for an account at https://gerrit.twrp.me and I can give you access to push to github through our gerrit instance.

**Comment by huckleberrypie** [comment]
There, already did. Care to walk me through as I am new to this?

**Comment by bigbiff** [comment]
Hello, here is a guide: https://forum.xda-developers.com/showthread.php?t=2628545

Our gerrit server is https://gerrit.twrp.me, ssh is ssh://username@gerrit.twrp.me:29418

We use the github auth API to authenticate with your github username.

The project is twrpme and you would push to HEAD:refs/for/master

**Comment by huckleberrypie** [comment]
Got it now, thanks!

**Pull request closed without merging**
